/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jbl_stc_com_activity_DashboardActivity_DashboardHandler */

#ifndef _Included_jbl_stc_com_activity_DashboardActivity_DashboardHandler
#define _Included_jbl_stc_com_activity_DashboardActivity_DashboardHandler
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif
