/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jbl_stc_com_activity_DashboardActivity */

#ifndef _Included_jbl_stc_com_activity_DashboardActivity
#define _Included_jbl_stc_com_activity_DashboardActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef jbl_stc_com_activity_DashboardActivity_MSG_SHOW_MY_PRODUCTS
#define jbl_stc_com_activity_DashboardActivity_MSG_SHOW_MY_PRODUCTS 0L
#undef jbl_stc_com_activity_DashboardActivity_MSG_SHOW_HOME_FRAGMENT
#define jbl_stc_com_activity_DashboardActivity_MSG_SHOW_HOME_FRAGMENT 1L
#undef jbl_stc_com_activity_DashboardActivity_MSG_SHOW_DISCOVERY
#define jbl_stc_com_activity_DashboardActivity_MSG_SHOW_DISCOVERY 2L
#undef jbl_stc_com_activity_DashboardActivity_MSG_START_SCAN
#define jbl_stc_com_activity_DashboardActivity_MSG_START_SCAN 4L
#undef jbl_stc_com_activity_DashboardActivity_MSG_SHOW_PLUS_ANIMATION_UP
#define jbl_stc_com_activity_DashboardActivity_MSG_SHOW_PLUS_ANIMATION_UP 5L
#undef jbl_stc_com_activity_DashboardActivity_MSG_SHOW_PLUS_ANIMATION_DOWN
#define jbl_stc_com_activity_DashboardActivity_MSG_SHOW_PLUS_ANIMATION_DOWN 6L
/*
 * Class:     jbl_stc_com_activity_DashboardActivity
 * Method:    calculateCalib
 * Signature: (Ljbl/stc/com/entity/designer_cfg;[Ljbl/stc/com/entity/IIR_PARAM_T;ILjbl/stc/com/entity/designer_cfg;[Ljbl/stc/com/entity/IIR_PARAM_T;I)F
 */
JNIEXPORT jfloat JNICALL Java_jbl_stc_com_activity_DashboardActivity_calculateCalib
        (JNIEnv *, jobject, jobject, jobjectArray, jint, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
